# -*- coding: utf-8 -*-
from __future__ import unicode_literals

TEST_EVENT_DICT = [
    {'datetime': 'Thursday September 07 2016 20:30', 'home': 'Carolina Panthers', 'away': 'Denver Broncos', 'week': '1'},
    {'datetime': 'Sunday September 07 2016 13:00', 'home': 'Buffalo Bills', 'away': 'Baltimore Ravens', 'week': '1'},
    {'datetime': 'Sunday September 07 2016 13:00', 'home': 'Chicago Bears', 'away': 'Houston Texans', 'week': '1'},
    {'datetime': 'Sunday September 07 2016 13:00', 'home': 'Cincinnati Bengals', 'away': 'New York Jets', 'week': '1'},
    {'datetime': 'Sunday September 07 2016 13:00', 'home': 'Cleveland Browns', 'away': 'Philadelphia Eagles', 'week': '1'},
    {'datetime': 'Sunday September 07 2016 13:00', 'home': 'Green Bay Packers', 'away': 'Jacksonville Jaguars', 'week': '1'},
    {'datetime': 'Sunday September 08 2016 13:00', 'home': 'Minnesota Vikings', 'away': 'Tennessee Titans', 'week': '2'},
    {'datetime': 'Sunday September 08 2016 13:00', 'home': 'Oakland Raiders', 'away': 'New Orleans Saints', 'week': '2'},
    {'datetime': 'Sunday September 08 2016 13:00', 'home': 'San Diego Chargers', 'away': 'Kansas City Chiefs', 'week': '2'},
    {'datetime': 'Sunday September 08 2016 13:00', 'home': 'Tampa Bay Buccaneers', 'away': 'Atlanta Falcons', 'week': '2'},
    {'datetime': 'Sunday September 08 2016 16:05', 'home': 'Miami Dolphins', 'away': 'Seattle Seahawks', 'week': '2'},
    {'datetime': 'Sunday September 08 2016 16:25', 'home': 'Detroit Lions', 'away': 'Indianapolis Colts', 'week': '2'},
    {'datetime': 'Sunday September 09 2016 16:25', 'home': 'New York Giants', 'away': 'Dallas Cowboys', 'week': '3'},
    {'datetime': 'Sunday September 09 2016 20:30', 'home': 'New England Patriots', 'away': 'Arizona Cardinals', 'week': '3'},
    {'datetime': 'Monday September 09 2016 19:10', 'home': 'Pittsburgh Steelers', 'away': 'Washington Redskins', 'week': '3'},
    {'datetime': 'Monday September 09 2016 22:20', 'home': 'Los Angeles Rams', 'away': 'San Francisco 49ers', 'week': '3'},
    {'datetime': 'Thursday September 09 2016 20:25', 'home': 'New York Jets', 'away': 'Buffalo Bills', 'week': '3'},
    {'datetime': 'Sunday September 09 2016 13:00', 'home': 'Baltimore Ravens', 'away': 'Cleveland Browns', 'week': '3'},
    {'datetime': 'Sunday September 10 2016 13:00', 'home': 'Cincinnati Bengals', 'away': 'Pittsburgh Steelers', 'week': '4'},
    {'datetime': 'Sunday September 10 2016 13:00', 'home': 'Dallas Cowboys', 'away': 'Washington Redskins', 'week': '4'},
    {'datetime': 'Sunday September 10 2016 13:00', 'home': 'Kansas City Chiefs', 'away': 'Houston Texans', 'week': '4'},
    {'datetime': 'Sunday September 10 2016 13:00', 'home': 'Miami Dolphins', 'away': 'New England Patriots', 'week': '4'},
    {'datetime': 'Sunday September 10 2016 13:00', 'home': 'New Orleans Saints', 'away': 'New York Giants', 'week': '4'},
    {'datetime': 'Sunday September 10 2016 13:00', 'home': 'San Francisco 49ers', 'away': 'Carolina Panthers', 'week': '4'},
    {'datetime': 'Sunday September 11 2016 13:00', 'home': 'Tennessee Titans', 'away': 'Detroit Lions', 'week': '5'},
    {'datetime': 'Sunday September 11 2016 16:05', 'home': 'Seattle Seahawks', 'away': 'Los Angeles Rams', 'week': '5'},
    {'datetime': 'Sunday September 11 2016 16:05', 'home': 'Tampa Bay Buccaneers', 'away': 'Arizona Cardinals', 'week': '5'},
    {'datetime': 'Sunday September 11 2016 16:25', 'home': 'Atlanta Falcons', 'away': 'Oakland Raiders', 'week': '5'},
    {'datetime': 'Sunday September 11 2016 16:25', 'home': 'Indianapolis Colts', 'away': 'Denver Broncos', 'week': '5'},
    {'datetime': 'Sunday September 11 2016 16:25', 'home': 'Jacksonville Jaguars', 'away': 'San Diego Chargers', 'week': '5'},
    {'datetime': 'Sunday September 12 2016 20:30', 'home': 'Green Bay Packers', 'away': 'Minnesota Vikings', 'week': '6'},
    {'datetime': 'Monday September 12 2016 20:30', 'home': 'Philadelphia Eagles', 'away': 'Chicago Bears', 'week': '6'},
    {'datetime': 'Thursday September 12 2016 20:25', 'home': 'Houston Texans', 'away': 'New England Patriots', 'week': '6'},
    {'datetime': 'Sunday September 12 2016 13:00', 'home': 'Arizona Cardinals', 'away': 'Buffalo Bills', 'week': '6'},
    {'datetime': 'Sunday September 12 2016 13:00', 'home': 'Baltimore Ravens', 'away': 'Jacksonville Jaguars', 'week': '6'},
    {'datetime': 'Sunday September 13 2016 13:00', 'home': 'Cleveland Browns', 'away': 'Miami Dolphins', 'week': '7'},
    {'datetime': 'Sunday September 13 2016 13:00', 'home': 'Denver Broncos', 'away': 'Cincinnati Bengals', 'week': '7'},
    {'datetime': 'Sunday September 13 2016 13:00', 'home': 'Detroit Lions', 'away': 'Green Bay Packers', 'week': '7'},
    {'datetime': 'Sunday September 13 2016 13:00', 'home': 'Minnesota Vikings', 'away': 'Carolina Panthers', 'week': '7'},
    {'datetime': 'Sunday September 13 2016 13:00', 'home': 'Oakland Raiders', 'away': 'Tennessee Titans', 'week': '7'},
]
