# -*- coding: utf-8 -*-
from __future__ import unicode_literals

EVENTS = [
    {'datetime': 'Thursday September 08 2016 20:30', 'home': 'Carolina Panthers', 'away': 'Denver Broncos', 'week': '1'},
    {'datetime': 'Sunday September 11 2016 13:00', 'home': 'Buffalo Bills', 'away': 'Baltimore Ravens', 'week': '1'},
    {'datetime': 'Sunday September 11 2016 13:00', 'home': 'Chicago Bears', 'away': 'Houston Texans', 'week': '1'},
    {'datetime': 'Sunday September 11 2016 13:00', 'home': 'Cincinnati Bengals', 'away': 'New York Jets', 'week': '1'},
    {'datetime': 'Sunday September 11 2016 13:00', 'home': 'Cleveland Browns', 'away': 'Philadelphia Eagles', 'week': '1'},
    {'datetime': 'Sunday September 11 2016 13:00', 'home': 'Green Bay Packers', 'away': 'Jacksonville Jaguars', 'week': '1'},
    {'datetime': 'Sunday September 11 2016 13:00', 'home': 'Minnesota Vikings', 'away': 'Tennessee Titans', 'week': '1'},
    {'datetime': 'Sunday September 11 2016 13:00', 'home': 'Oakland Raiders', 'away': 'New Orleans Saints', 'week': '1'},
    {'datetime': 'Sunday September 11 2016 13:00', 'home': 'San Diego Chargers', 'away': 'Kansas City Chiefs', 'week': '1'},
    {'datetime': 'Sunday September 11 2016 13:00', 'home': 'Tampa Bay Buccaneers', 'away': 'Atlanta Falcons', 'week': '1'},
    {'datetime': 'Sunday September 11 2016 16:05', 'home': 'Miami Dolphins', 'away': 'Seattle Seahawks', 'week': '1'},
    {'datetime': 'Sunday September 11 2016 16:25', 'home': 'Detroit Lions', 'away': 'Indianapolis Colts', 'week': '1'},
    {'datetime': 'Sunday September 11 2016 16:25', 'home': 'New York Giants', 'away': 'Dallas Cowboys', 'week': '1'},
    {'datetime': 'Sunday September 11 2016 20:30', 'home': 'New England Patriots', 'away': 'Arizona Cardinals', 'week': '1'},
    {'datetime': 'Monday September 12 2016 19:10', 'home': 'Pittsburgh Steelers', 'away': 'Washington Redskins', 'week': '1'},
    {'datetime': 'Monday September 12 2016 22:20', 'home': 'Los Angeles Rams', 'away': 'San Francisco 49ers', 'week': '1'},
    {'datetime': 'Thursday September 15 2016 20:25', 'home': 'New York Jets', 'away': 'Buffalo Bills', 'week': '2'},
    {'datetime': 'Sunday September 18 2016 13:00', 'home': 'Baltimore Ravens', 'away': 'Cleveland Browns', 'week': '2'},
    {'datetime': 'Sunday September 18 2016 13:00', 'home': 'Cincinnati Bengals', 'away': 'Pittsburgh Steelers', 'week': '2'},
    {'datetime': 'Sunday September 18 2016 13:00', 'home': 'Dallas Cowboys', 'away': 'Washington Redskins', 'week': '2'},
    {'datetime': 'Sunday September 18 2016 13:00', 'home': 'Kansas City Chiefs', 'away': 'Houston Texans', 'week': '2'},
    {'datetime': 'Sunday September 18 2016 13:00', 'home': 'Miami Dolphins', 'away': 'New England Patriots', 'week': '2'},
    {'datetime': 'Sunday September 18 2016 13:00', 'home': 'New Orleans Saints', 'away': 'New York Giants', 'week': '2'},
    {'datetime': 'Sunday September 18 2016 13:00', 'home': 'San Francisco 49ers', 'away': 'Carolina Panthers', 'week': '2'},
    {'datetime': 'Sunday September 18 2016 13:00', 'home': 'Tennessee Titans', 'away': 'Detroit Lions', 'week': '2'},
    {'datetime': 'Sunday September 18 2016 16:05', 'home': 'Seattle Seahawks', 'away': 'Los Angeles Rams', 'week': '2'},
    {'datetime': 'Sunday September 18 2016 16:05', 'home': 'Tampa Bay Buccaneers', 'away': 'Arizona Cardinals', 'week': '2'},
    {'datetime': 'Sunday September 18 2016 16:25', 'home': 'Atlanta Falcons', 'away': 'Oakland Raiders', 'week': '2'},
    {'datetime': 'Sunday September 18 2016 16:25', 'home': 'Indianapolis Colts', 'away': 'Denver Broncos', 'week': '2'},
    {'datetime': 'Sunday September 18 2016 16:25', 'home': 'Jacksonville Jaguars', 'away': 'San Diego Chargers', 'week': '2'},
    {'datetime': 'Sunday September 18 2016 20:30', 'home': 'Green Bay Packers', 'away': 'Minnesota Vikings', 'week': '2'},
    {'datetime': 'Monday September 19 2016 20:30', 'home': 'Philadelphia Eagles', 'away': 'Chicago Bears', 'week': '2'},
    {'datetime': 'Thursday September 22 2016 20:25', 'home': 'Houston Texans', 'away': 'New England Patriots', 'week': '3'},
    {'datetime': 'Sunday September 25 2016 13:00', 'home': 'Arizona Cardinals', 'away': 'Buffalo Bills', 'week': '3'},
    {'datetime': 'Sunday September 25 2016 13:00', 'home': 'Baltimore Ravens', 'away': 'Jacksonville Jaguars', 'week': '3'},
    {'datetime': 'Sunday September 25 2016 13:00', 'home': 'Cleveland Browns', 'away': 'Miami Dolphins', 'week': '3'},
    {'datetime': 'Sunday September 25 2016 13:00', 'home': 'Denver Broncos', 'away': 'Cincinnati Bengals', 'week': '3'},
    {'datetime': 'Sunday September 25 2016 13:00', 'home': 'Detroit Lions', 'away': 'Green Bay Packers', 'week': '3'},
    {'datetime': 'Sunday September 25 2016 13:00', 'home': 'Minnesota Vikings', 'away': 'Carolina Panthers', 'week': '3'},
    {'datetime': 'Sunday September 25 2016 13:00', 'home': 'Oakland Raiders', 'away': 'Tennessee Titans', 'week': '3'},
    {'datetime': 'Sunday September 25 2016 13:00', 'home': 'Washington Redskins', 'away': 'New York Giants', 'week': '3'},
    {'datetime': 'Sunday September 25 2016 16:05', 'home': 'Los Angeles Rams', 'away': 'Tampa Bay Buccaneers', 'week': '3'},
    {'datetime': 'Sunday September 25 2016 16:05', 'home': 'San Francisco 49ers', 'away': 'Seattle Seahawks', 'week': '3'},
    {'datetime': 'Sunday September 25 2016 16:25', 'home': 'New York Jets', 'away': 'Kansas City Chiefs', 'week': '3'},
    {'datetime': 'Sunday September 25 2016 16:25', 'home': 'Pittsburgh Steelers', 'away': 'Philadelphia Eagles', 'week': '3'},
    {'datetime': 'Sunday September 25 2016 16:25', 'home': 'San Diego Chargers', 'away': 'Indianapolis Colts', 'week': '3'},
    {'datetime': 'Sunday September 25 2016 20:30', 'home': 'Chicago Bears', 'away': 'Dallas Cowboys', 'week': '3'},
    {'datetime': 'Monday September 26 2016 20:30', 'home': 'Atlanta Falcons', 'away': 'New Orleans Saints', 'week': '3'},
    {'datetime': 'Thursday September 29 2016 20:25', 'home': 'Miami Dolphins', 'away': 'Cincinnati Bengals', 'week': '4'},
    {'datetime': 'Sunday October 02 2016 09:30', 'home': 'Indianapolis Colts', 'away': 'Jacksonville Jaguars _', 'week': '4'},
    {'datetime': 'Sunday October 02 2016 13:00', 'home': 'Buffalo Bills', 'away': 'New England Patriots', 'week': '4'},
    {'datetime': 'Sunday October 02 2016 13:00', 'home': 'Carolina Panthers', 'away': 'Atlanta Falcons', 'week': '4'},
    {'datetime': 'Sunday October 02 2016 13:00', 'home': 'Cleveland Browns', 'away': 'Washington Redskins', 'week': '4'},
    {'datetime': 'Sunday October 02 2016 13:00', 'home': 'Detroit Lions', 'away': 'Chicago Bears', 'week': '4'},
    {'datetime': 'Sunday October 02 2016 13:00', 'home': 'Oakland Raiders', 'away': 'Baltimore Ravens', 'week': '4'},
    {'datetime': 'Sunday October 02 2016 13:00', 'home': 'Seattle Seahawks', 'away': 'New York Jets', 'week': '4'},
    {'datetime': 'Sunday October 02 2016 13:00', 'home': 'Tennessee Titans', 'away': 'Houston Texans', 'week': '4'},
    {'datetime': 'Sunday October 02 2016 16:05', 'home': 'Denver Broncos', 'away': 'Tampa Bay Buccaneers', 'week': '4'},
    {'datetime': 'Sunday October 02 2016 16:25', 'home': 'Dallas Cowboys', 'away': 'San Francisco 49ers', 'week': '4'},
    {'datetime': 'Sunday October 02 2016 16:25', 'home': 'Los Angeles Rams', 'away': 'Arizona Cardinals', 'week': '4'},
    {'datetime': 'Sunday October 02 2016 16:25', 'home': 'New Orleans Saints', 'away': 'San Diego Chargers', 'week': '4'},
    {'datetime': 'Sunday October 02 2016 20:30', 'home': 'Kansas City Chiefs', 'away': 'Pittsburgh Steelers', 'week': '4'},
    {'datetime': 'Monday October 03 2016 20:30', 'home': 'New York Giants', 'away': 'Minnesota Vikings', 'week': '4'},
    {'datetime': 'Thursday October 06 2016 20:25', 'home': 'Arizona Cardinals', 'away': 'San Francisco 49ers', 'week': '5'},
    {'datetime': 'Sunday October 09 2016 13:00', 'home': 'Chicago Bears', 'away': 'Indianapolis Colts', 'week': '5'},
    {'datetime': 'Sunday October 09 2016 13:00', 'home': 'Houston Texans', 'away': 'Minnesota Vikings', 'week': '5'},
    {'datetime': 'Sunday October 09 2016 13:00', 'home': 'New England Patriots', 'away': 'Cleveland Browns', 'week': '5'},
    {'datetime': 'Sunday October 09 2016 13:00', 'home': 'New York Jets', 'away': 'Pittsburgh Steelers', 'week': '5'},
    {'datetime': 'Sunday October 09 2016 13:00', 'home': 'Philadelphia Eagles', 'away': 'Detroit Lions', 'week': '5'},
    {'datetime': 'Sunday October 09 2016 13:00', 'home': 'Tennessee Titans', 'away': 'Miami Dolphins', 'week': '5'},
    {'datetime': 'Sunday October 09 2016 13:00', 'home': 'Washington Redskins', 'away': 'Baltimore Ravens', 'week': '5'},
    {'datetime': 'Sunday October 09 2016 16:05', 'home': 'Atlanta Falcons', 'away': 'Denver Broncos', 'week': '5'},
    {'datetime': 'Sunday October 09 2016 16:25', 'home': 'Buffalo Bills', 'away': 'Los Angeles Rams', 'week': '5'},
    {'datetime': 'Sunday October 09 2016 16:25', 'home': 'Cincinnati Bengals', 'away': 'Dallas Cowboys', 'week': '5'},
    {'datetime': 'Sunday October 09 2016 16:25', 'home': 'San Diego Chargers', 'away': 'Oakland Raiders', 'week': '5'},
    {'datetime': 'Sunday October 09 2016 20:30', 'home': 'New York Giants', 'away': 'Green Bay Packers', 'week': '5'},
    {'datetime': 'Monday October 10 2016 20:30', 'home': 'Tampa Bay Buccaneers', 'away': 'Carolina Panthers', 'week': '5'},
    {'datetime': 'Thursday October 13 2016 20:25', 'home': 'Denver Broncos', 'away': 'San Diego Chargers', 'week': '6'},
    {'datetime': 'Sunday October 16 2016 13:00', 'home': 'Baltimore Ravens', 'away': 'New York Giants', 'week': '6'},
    {'datetime': 'Sunday October 16 2016 13:00', 'home': 'Carolina Panthers', 'away': 'New Orleans Saints', 'week': '6'},
    {'datetime': 'Sunday October 16 2016 13:00', 'home': 'Cincinnati Bengals', 'away': 'New England Patriots', 'week': '6'},
    {'datetime': 'Sunday October 16 2016 13:00', 'home': 'Cleveland Browns', 'away': 'Tennessee Titans', 'week': '6'},
    {'datetime': 'Sunday October 16 2016 13:00', 'home': 'Jacksonville Jaguars', 'away': 'Chicago Bears', 'week': '6'},
    {'datetime': 'Sunday October 16 2016 13:00', 'home': 'Los Angeles Rams', 'away': 'Detroit Lions', 'week': '6'},
    {'datetime': 'Sunday October 16 2016 13:00', 'home': 'Philadelphia Eagles', 'away': 'Washington Redskins', 'week': '6'},
    {'datetime': 'Sunday October 16 2016 13:00', 'home': 'Pittsburgh Steelers', 'away': 'Miami Dolphins', 'week': '6'},
    {'datetime': 'Sunday October 16 2016 13:00', 'home': 'San Francisco 49ers', 'away': 'Buffalo Bills', 'week': '6'},
    {'datetime': 'Sunday October 16 2016 16:05', 'home': 'Kansas City Chiefs', 'away': 'Oakland Raiders', 'week': '6'},
    {'datetime': 'Sunday October 16 2016 16:25', 'home': 'Atlanta Falcons', 'away': 'Seattle Seahawks', 'week': '6'},
    {'datetime': 'Sunday October 16 2016 16:25', 'home': 'Dallas Cowboys', 'away': 'Green Bay Packers', 'week': '6'},
    {'datetime': 'Sunday October 16 2016 20:30', 'home': 'Indianapolis Colts', 'away': 'Houston Texans', 'week': '6'},
    {'datetime': 'Monday October 17 2016 20:30', 'home': 'New York Jets', 'away': 'Arizona Cardinals', 'week': '6'},
    {'datetime': 'Thursday October 20 2016 20:25', 'home': 'Chicago Bears', 'away': 'Green Bay Packers', 'week': '7'},
    {'datetime': 'Sunday October 23 2016 09:30', 'home': 'New York Giants', 'away': 'Los Angeles Rams _', 'week': '7'},
    {'datetime': 'Sunday October 23 2016 13:00', 'home': 'Baltimore Ravens', 'away': 'New York Jets', 'week': '7'},
    {'datetime': 'Sunday October 23 2016 13:00', 'home': 'Buffalo Bills', 'away': 'Miami Dolphins', 'week': '7'},
    {'datetime': 'Sunday October 23 2016 13:00', 'home': 'Cleveland Browns', 'away': 'Cincinnati Bengals', 'week': '7'},
    {'datetime': 'Sunday October 23 2016 13:00', 'home': 'Indianapolis Colts', 'away': 'Tennessee Titans', 'week': '7'},
    {'datetime': 'Sunday October 23 2016 13:00', 'home': 'Minnesota Vikings', 'away': 'Philadelphia Eagles', 'week': '7'},
    {'datetime': 'Sunday October 23 2016 13:00', 'home': 'New Orleans Saints', 'away': 'Kansas City Chiefs', 'week': '7'},
    {'datetime': 'Sunday October 23 2016 13:00', 'home': 'Oakland Raiders', 'away': 'Jacksonville Jaguars', 'week': '7'},
    {'datetime': 'Sunday October 23 2016 13:00', 'home': 'Washington Redskins', 'away': 'Detroit Lions', 'week': '7'},
    {'datetime': 'Sunday October 23 2016 16:05', 'home': 'San Diego Chargers', 'away': 'Atlanta Falcons', 'week': '7'},
    {'datetime': 'Sunday October 23 2016 16:05', 'home': 'Tampa Bay Buccaneers', 'away': 'San Francisco 49ers', 'week': '7'},
    {'datetime': 'Sunday October 23 2016 16:25', 'home': 'New England Patriots', 'away': 'Pittsburgh Steelers', 'week': '7'},
    {'datetime': 'Sunday October 23 2016 20:30', 'home': 'Seattle Seahawks', 'away': 'Arizona Cardinals', 'week': '7'},
    {'datetime': 'Monday October 24 2016 20:30', 'home': 'Houston Texans', 'away': 'Denver Broncos', 'week': '7'},
    {'datetime': 'Thursday October 27 2016 20:25', 'home': 'Jacksonville Jaguars', 'away': 'Tennessee Titans', 'week': '8'},
    {'datetime': 'Sunday October 30 2016 09:30', 'home': 'Washington Redskins', 'away': 'Cincinnati Bengals _', 'week': '8'},
    {'datetime': 'Sunday October 30 2016 13:00', 'home': 'Detroit Lions', 'away': 'Houston Texans', 'week': '8'},
    {'datetime': 'Sunday October 30 2016 13:00', 'home': 'Green Bay Packers', 'away': 'Atlanta Falcons', 'week': '8'},
    {'datetime': 'Sunday October 30 2016 13:00', 'home': 'Kansas City Chiefs', 'away': 'Indianapolis Colts', 'week': '8'},
    {'datetime': 'Sunday October 30 2016 13:00', 'home': 'New England Patriots', 'away': 'Buffalo Bills', 'week': '8'},
    {'datetime': 'Sunday October 30 2016 13:00', 'home': 'New York Jets', 'away': 'Cleveland Browns', 'week': '8'},
    {'datetime': 'Sunday October 30 2016 13:00', 'home': 'Oakland Raiders', 'away': 'Tampa Bay Buccaneers', 'week': '8'},
    {'datetime': 'Sunday October 30 2016 13:00', 'home': 'Seattle Seahawks', 'away': 'New Orleans Saints', 'week': '8'},
    {'datetime': 'Sunday October 30 2016 16:05', 'home': 'San Diego Chargers', 'away': 'Denver Broncos', 'week': '8'},
    {'datetime': 'Sunday October 30 2016 16:25', 'home': 'Arizona Cardinals', 'away': 'Carolina Panthers', 'week': '8'},
    {'datetime': 'Sunday October 30 2016 20:30', 'home': 'Philadelphia Eagles', 'away': 'Dallas Cowboys', 'week': '8'},
    {'datetime': 'Monday October 31 2016 20:30', 'home': 'Minnesota Vikings', 'away': 'Chicago Bears', 'week': '8'},
    {'datetime': 'Thursday November 03 2016 20:25', 'home': 'Atlanta Falcons', 'away': 'Tampa Bay Buccaneers', 'week': '9'},
    {'datetime': 'Sunday November 06 2016 13:00', 'home': 'Dallas Cowboys', 'away': 'Cleveland Browns', 'week': '9'},
    {'datetime': 'Sunday November 06 2016 13:00', 'home': 'Detroit Lions', 'away': 'Minnesota Vikings', 'week': '9'},
    {'datetime': 'Sunday November 06 2016 13:00', 'home': 'Jacksonville Jaguars', 'away': 'Kansas City Chiefs', 'week': '9'},
    {'datetime': 'Sunday November 06 2016 13:00', 'home': 'New York Jets', 'away': 'Miami Dolphins', 'week': '9'},
    {'datetime': 'Sunday November 06 2016 13:00', 'home': 'Philadelphia Eagles', 'away': 'New York Giants', 'week': '9'},
    {'datetime': 'Sunday November 06 2016 13:00', 'home': 'Pittsburgh Steelers', 'away': 'Baltimore Ravens', 'week': '9'},
    {'datetime': 'Sunday November 06 2016 16:05', 'home': 'Carolina Panthers', 'away': 'Los Angeles Rams', 'week': '9'},
    {'datetime': 'Sunday November 06 2016 16:05', 'home': 'New Orleans Saints', 'away': 'San Francisco 49ers', 'week': '9'},
    {'datetime': 'Sunday November 06 2016 16:25', 'home': 'Indianapolis Colts', 'away': 'Green Bay Packers', 'week': '9'},
    {'datetime': 'Sunday November 06 2016 16:25', 'home': 'Tennessee Titans', 'away': 'San Diego Chargers', 'week': '9'},
    {'datetime': 'Sunday November 06 2016 20:30', 'home': 'Denver Broncos', 'away': 'Oakland Raiders', 'week': '9'},
    {'datetime': 'Monday November 07 2016 20:30', 'home': 'Buffalo Bills', 'away': 'Seattle Seahawks', 'week': '9'},
    {'datetime': 'Thursday November 10 2016 20:25', 'home': 'Cleveland Browns', 'away': 'Baltimore Ravens', 'week': '10'},
    {'datetime': 'Sunday November 13 2016 13:00', 'home': 'Atlanta Falcons', 'away': 'Philadelphia Eagles', 'week': '10'},
    {'datetime': 'Sunday November 13 2016 13:00', 'home': 'Chicago Bears', 'away': 'Tampa Bay Buccaneers', 'week': '10'},
    {'datetime': 'Sunday November 13 2016 13:00', 'home': 'Denver Broncos', 'away': 'New Orleans Saints', 'week': '10'},
    {'datetime': 'Sunday November 13 2016 13:00', 'home': 'Green Bay Packers', 'away': 'Tennessee Titans', 'week': '10'},
    {'datetime': 'Sunday November 13 2016 13:00', 'home': 'Houston Texans', 'away': 'Jacksonville Jaguars', 'week': '10'},
    {'datetime': 'Sunday November 13 2016 13:00', 'home': 'Kansas City Chiefs', 'away': 'Carolina Panthers', 'week': '10'},
    {'datetime': 'Sunday November 13 2016 13:00', 'home': 'Los Angeles Rams', 'away': 'New York Jets', 'week': '10'},
    {'datetime': 'Sunday November 13 2016 13:00', 'home': 'Minnesota Vikings', 'away': 'Washington Redskins', 'week': '10'},
    {'datetime': 'Sunday November 13 2016 16:05', 'home': 'Miami Dolphins', 'away': 'San Diego Chargers', 'week': '10'},
    {'datetime': 'Sunday November 13 2016 16:25', 'home': 'Dallas Cowboys', 'away': 'Pittsburgh Steelers', 'week': '10'},
    {'datetime': 'Sunday November 13 2016 16:25', 'home': 'San Francisco 49ers', 'away': 'Arizona Cardinals', 'week': '10'},
    {'datetime': 'Sunday November 13 2016 20:30', 'home': 'Seattle Seahawks', 'away': 'New England Patriots', 'week': '10'},
    {'datetime': 'Monday November 14 2016 20:30', 'home': 'Cincinnati Bengals', 'away': 'New York Giants', 'week': '10'},
    {'datetime': 'Thursday November 17 2016 20:25', 'home': 'New Orleans Saints', 'away': 'Carolina Panthers', 'week': '11'},
    {'datetime': 'Sunday November 20 2016 13:00', 'home': 'Arizona Cardinals', 'away': 'Minnesota Vikings', 'week': '11'},
    {'datetime': 'Sunday November 20 2016 13:00', 'home': 'Baltimore Ravens', 'away': 'Dallas Cowboys', 'week': '11'},
    {'datetime': 'Sunday November 20 2016 13:00', 'home': 'Buffalo Bills', 'away': 'Cincinnati Bengals', 'week': '11'},
    {'datetime': 'Sunday November 20 2016 13:00', 'home': 'Chicago Bears', 'away': 'New York Giants', 'week': '11'},
    {'datetime': 'Sunday November 20 2016 13:00', 'home': 'Jacksonville Jaguars', 'away': 'Detroit Lions', 'week': '11'},
    {'datetime': 'Sunday November 20 2016 13:00', 'home': 'Pittsburgh Steelers', 'away': 'Cleveland Browns', 'week': '11'},
    {'datetime': 'Sunday November 20 2016 13:00', 'home': 'Tampa Bay Buccaneers', 'away': 'Kansas City Chiefs', 'week': '11'},
    {'datetime': 'Sunday November 20 2016 13:00', 'home': 'Tennessee Titans', 'away': 'Indianapolis Colts', 'week': '11'},
    {'datetime': 'Sunday November 20 2016 16:05', 'home': 'Miami Dolphins', 'away': 'Los Angeles Rams', 'week': '11'},
    {'datetime': 'Sunday November 20 2016 16:25', 'home': 'New England Patriots', 'away': 'San Francisco 49ers', 'week': '11'},
    {'datetime': 'Sunday November 20 2016 16:25', 'home': 'Philadelphia Eagles', 'away': 'Seattle Seahawks', 'week': '11'},
    {'datetime': 'Sunday November 20 2016 20:30', 'home': 'Green Bay Packers', 'away': 'Washington Redskins', 'week': '11'},
    {'datetime': 'Monday November 21 2016 20:30', 'home': 'Houston Texans', 'away': 'Oakland Raiders', 'week': '11'},
    {'datetime': 'Thursday November 24 2016 12:30', 'home': 'Minnesota Vikings', 'away': 'Detroit Lions', 'week': '12'},
    {'datetime': 'Thursday November 24 2016 16:30', 'home': 'Washington Redskins', 'away': 'Dallas Cowboys', 'week': '12'},
    {'datetime': 'Thursday November 24 2016 20:30', 'home': 'Pittsburgh Steelers', 'away': 'Indianapolis Colts', 'week': '12'},
    {'datetime': 'Sunday November 27 2016 13:00', 'home': 'Arizona Cardinals', 'away': 'Atlanta Falcons', 'week': '12'},
    {'datetime': 'Sunday November 27 2016 13:00', 'home': 'Cincinnati Bengals', 'away': 'Baltimore Ravens', 'week': '12'},
    {'datetime': 'Sunday November 27 2016 13:00', 'home': 'Jacksonville Jaguars', 'away': 'Buffalo Bills', 'week': '12'},
    {'datetime': 'Sunday November 27 2016 13:00', 'home': 'Los Angeles Rams', 'away': 'New Orleans Saints', 'week': '12'},
    {'datetime': 'Sunday November 27 2016 13:00', 'home': 'New York Giants', 'away': 'Cleveland Browns', 'week': '12'},
    {'datetime': 'Sunday November 27 2016 13:00', 'home': 'San Diego Chargers', 'away': 'Houston Texans', 'week': '12'},
    {'datetime': 'Sunday November 27 2016 13:00', 'home': 'San Francisco 49ers', 'away': 'Miami Dolphins', 'week': '12'},
    {'datetime': 'Sunday November 27 2016 13:00', 'home': 'Tennessee Titans', 'away': 'Chicago Bears', 'week': '12'},
    {'datetime': 'Sunday November 27 2016 16:05', 'home': 'Seattle Seahawks', 'away': 'Tampa Bay Buccaneers', 'week': '12'},
    {'datetime': 'Sunday November 27 2016 16:25', 'home': 'Carolina Panthers', 'away': 'Oakland Raiders', 'week': '12'},
    {'datetime': 'Sunday November 27 2016 16:25', 'home': 'Kansas City Chiefs', 'away': 'Denver Broncos', 'week': '12'},
    {'datetime': 'Sunday November 27 2016 20:30', 'home': 'New England Patriots', 'away': 'New York Jets', 'week': '12'},
    {'datetime': 'Monday November 28 2016 20:30', 'home': 'Green Bay Packers', 'away': 'Philadelphia Eagles', 'week': '12'},
    {'datetime': 'Thursday December 01 2016 20:25', 'home': 'Dallas Cowboys', 'away': 'Minnesota Vikings', 'week': '13'},
    {'datetime': 'Sunday December 04 2016 13:00', 'home': 'Denver Broncos', 'away': 'Jacksonville Jaguars', 'week': '13'},
    {'datetime': 'Sunday December 04 2016 13:00', 'home': 'Detroit Lions', 'away': 'New Orleans Saints', 'week': '13'},
    {'datetime': 'Sunday December 04 2016 13:00', 'home': 'Houston Texans', 'away': 'Green Bay Packers', 'week': '13'},
    {'datetime': 'Sunday December 04 2016 13:00', 'home': 'Kansas City Chiefs', 'away': 'Atlanta Falcons', 'week': '13'},
    {'datetime': 'Sunday December 04 2016 13:00', 'home': 'Los Angeles Rams', 'away': 'New England Patriots', 'week': '13'},
    {'datetime': 'Sunday December 04 2016 13:00', 'home': 'Miami Dolphins', 'away': 'Baltimore Ravens', 'week': '13'},
    {'datetime': 'Sunday December 04 2016 13:00', 'home': 'Philadelphia Eagles', 'away': 'Cincinnati Bengals', 'week': '13'},
    {'datetime': 'Sunday December 04 2016 13:00', 'home': 'San Francisco 49ers', 'away': 'Chicago Bears', 'week': '13'},
    {'datetime': 'Sunday December 04 2016 16:05', 'home': 'Buffalo Bills', 'away': 'Oakland Raiders', 'week': '13'},
    {'datetime': 'Sunday December 04 2016 16:25', 'home': 'New York Giants', 'away': 'Pittsburgh Steelers', 'week': '13'},
    {'datetime': 'Sunday December 04 2016 16:25', 'home': 'Tampa Bay Buccaneers', 'away': 'San Diego Chargers', 'week': '13'},
    {'datetime': 'Sunday December 04 2016 16:25', 'home': 'Washington Redskins', 'away': 'Arizona Cardinals', 'week': '13'},
    {'datetime': 'Sunday December 04 2016 20:30', 'home': 'Carolina Panthers', 'away': 'Seattle Seahawks', 'week': '13'},
    {'datetime': 'Monday December 05 2016 20:30', 'home': 'Indianapolis Colts', 'away': 'New York Jets', 'week': '13'},
    {'datetime': 'Thursday December 08 2016 20:25', 'home': 'Oakland Raiders', 'away': 'Kansas City Chiefs', 'week': '14'},
    {'datetime': 'Sunday December 11 2016 13:00', 'home': 'Arizona Cardinals', 'away': 'Miami Dolphins', 'week': '14'},
    {'datetime': 'Sunday December 11 2016 13:00', 'home': 'Chicago Bears', 'away': 'Detroit Lions', 'week': '14'},
    {'datetime': 'Sunday December 11 2016 13:00', 'home': 'Cincinnati Bengals', 'away': 'Cleveland Browns', 'week': '14'},
    {'datetime': 'Sunday December 11 2016 13:00', 'home': 'Denver Broncos', 'away': 'Tennessee Titans', 'week': '14'},
    {'datetime': 'Sunday December 11 2016 13:00', 'home': 'Houston Texans', 'away': 'Indianapolis Colts', 'week': '14'},
    {'datetime': 'Sunday December 11 2016 13:00', 'home': 'Minnesota Vikings', 'away': 'Jacksonville Jaguars', 'week': '14'},
    {'datetime': 'Sunday December 11 2016 13:00', 'home': 'New Orleans Saints', 'away': 'Tampa Bay Buccaneers', 'week': '14'},
    {'datetime': 'Sunday December 11 2016 13:00', 'home': 'Pittsburgh Steelers', 'away': 'Buffalo Bills', 'week': '14'},
    {'datetime': 'Sunday December 11 2016 13:00', 'home': 'San Diego Chargers', 'away': 'Carolina Panthers', 'week': '14'},
    {'datetime': 'Sunday December 11 2016 13:00', 'home': 'Washington Redskins', 'away': 'Philadelphia Eagles', 'week': '14'},
    {'datetime': 'Sunday December 11 2016 16:05', 'home': 'New York Jets', 'away': 'San Francisco 49ers', 'week': '14'},
    {'datetime': 'Sunday December 11 2016 16:25', 'home': 'Atlanta Falcons', 'away': 'Los Angeles Rams', 'week': '14'},
    {'datetime': 'Sunday December 11 2016 16:25', 'home': 'Seattle Seahawks', 'away': 'Green Bay Packers', 'week': '14'},
    {'datetime': 'Sunday December 11 2016 20:30', 'home': 'Dallas Cowboys', 'away': 'New York Giants', 'week': '14'},
    {'datetime': 'Monday December 12 2016 20:30', 'home': 'Baltimore Ravens', 'away': 'New England Patriots', 'week': '14'},
    {'datetime': 'Thursday December 15 2016 20:25', 'home': 'Los Angeles Rams', 'away': 'Seattle Seahawks', 'week': '15'},
    {'datetime': 'Saturday December 17 2016 20:25', 'home': 'Miami Dolphins', 'away': 'New York Jets', 'week': '15'},
    {'datetime': 'Sunday December 18 2016 13:00', 'home': 'Cleveland Browns', 'away': 'Buffalo Bills', 'week': '15'},
    {'datetime': 'Sunday December 18 2016 13:00', 'home': 'Detroit Lions', 'away': 'New York Giants', 'week': '15'},
    {'datetime': 'Sunday December 18 2016 13:00', 'home': 'Green Bay Packers', 'away': 'Chicago Bears', 'week': '15'},
    {'datetime': 'Sunday December 18 2016 13:00', 'home': 'Indianapolis Colts', 'away': 'Minnesota Vikings', 'week': '15'},
    {'datetime': 'Sunday December 18 2016 13:00', 'home': 'Jacksonville Jaguars', 'away': 'Houston Texans', 'week': '15'},
    {'datetime': 'Sunday December 18 2016 13:00', 'home': 'Philadelphia Eagles', 'away': 'Baltimore Ravens', 'week': '15'},
    {'datetime': 'Sunday December 18 2016 13:00', 'home': 'Tampa Bay Buccaneers', 'away': 'Dallas Cowboys', 'week': '15'},
    {'datetime': 'Sunday December 18 2016 13:00', 'home': 'Tennessee Titans', 'away': 'Kansas City Chiefs', 'week': '15'},
    {'datetime': 'Sunday December 18 2016 16:05', 'home': 'New Orleans Saints', 'away': 'Arizona Cardinals', 'week': '15'},
    {'datetime': 'Sunday December 18 2016 16:05', 'home': 'San Francisco 49ers', 'away': 'Atlanta Falcons', 'week': '15'},
    {'datetime': 'Sunday December 18 2016 16:25', 'home': 'New England Patriots', 'away': 'Denver Broncos', 'week': '15'},
    {'datetime': 'Sunday December 18 2016 16:25', 'home': 'Oakland Raiders', 'away': 'San Diego Chargers', 'week': '15'},
    {'datetime': 'Sunday December 18 2016 20:30', 'home': 'Pittsburgh Steelers', 'away': 'Cincinnati Bengals', 'week': '15'},
    {'datetime': 'Monday December 19 2016 20:30', 'home': 'Carolina Panthers', 'away': 'Washington Redskins', 'week': '15'},
    {'datetime': 'Thursday December 22 2016 20:25', 'home': 'New York Giants', 'away': 'Philadelphia Eagles', 'week': '16'},
    {'datetime': 'Saturday December 24 2016 13:00', 'home': 'Atlanta Falcons', 'away': 'Carolina Panthers', 'week': '16'},
    {'datetime': 'Saturday December 24 2016 13:00', 'home': 'Miami Dolphins', 'away': 'Buffalo Bills', 'week': '16'},
    {'datetime': 'Saturday December 24 2016 13:00', 'home': 'Minnesota Vikings', 'away': 'Green Bay Packers', 'week': '16'},
    {'datetime': 'Saturday December 24 2016 13:00', 'home': 'New York Jets', 'away': 'New England Patriots', 'week': '16'},
    {'datetime': 'Saturday December 24 2016 13:00', 'home': 'San Diego Chargers', 'away': 'Cleveland Browns', 'week': '16'},
    {'datetime': 'Saturday December 24 2016 13:00', 'home': 'Tampa Bay Buccaneers', 'away': 'New Orleans Saints', 'week': '16'},
    {'datetime': 'Saturday December 24 2016 13:00', 'home': 'Tennessee Titans', 'away': 'Jacksonville Jaguars', 'week': '16'},
    {'datetime': 'Saturday December 24 2016 13:00', 'home': 'Washington Redskins', 'away': 'Chicago Bears', 'week': '16'},
    {'datetime': 'Saturday December 24 2016 16:05', 'home': 'Indianapolis Colts', 'away': 'Oakland Raiders', 'week': '16'},
    {'datetime': 'Saturday December 24 2016 16:25', 'home': 'Arizona Cardinals', 'away': 'Seattle Seahawks', 'week': '16'},
    {'datetime': 'Saturday December 24 2016 16:25', 'home': 'San Francisco 49ers', 'away': 'Los Angeles Rams', 'week': '16'},
    {'datetime': 'Saturday December 24 2016 20:25', 'home': 'Cincinnati Bengals', 'away': 'Houston Texans', 'week': '16'},
    {'datetime': 'Sunday December 25 2016 16:30', 'home': 'Baltimore Ravens', 'away': 'Pittsburgh Steelers', 'week': '16'},
    {'datetime': 'Sunday December 25 2016 20:30', 'home': 'Denver Broncos', 'away': 'Kansas City Chiefs', 'week': '16'},
    {'datetime': 'Monday December 26 2016 20:30', 'home': 'Detroit Lions', 'away': 'Dallas Cowboys', 'week': '16'},
    {'datetime': 'Sunday January 01 2017 13:00', 'home': 'Baltimore Ravens', 'away': 'Cincinnati Bengals', 'week': '17'},
    {'datetime': 'Sunday January 01 2017 13:00', 'home': 'Buffalo Bills', 'away': 'New York Jets', 'week': '17'},
    {'datetime': 'Sunday January 01 2017 13:00', 'home': 'Carolina Panthers', 'away': 'Tampa Bay Buccaneers', 'week': '17'},
    {'datetime': 'Sunday January 01 2017 13:00', 'home': 'Chicago Bears', 'away': 'Minnesota Vikings', 'week': '17'},
    {'datetime': 'Sunday January 01 2017 13:00', 'home': 'Cleveland Browns', 'away': 'Pittsburgh Steelers', 'week': '17'},
    {'datetime': 'Sunday January 01 2017 13:00', 'home': 'Dallas Cowboys', 'away': 'Philadelphia Eagles', 'week': '17'},
    {'datetime': 'Sunday January 01 2017 13:00', 'home': 'Green Bay Packers', 'away': 'Detroit Lions', 'week': '17'},
    {'datetime': 'Sunday January 01 2017 13:00', 'home': 'Houston Texans', 'away': 'Tennessee Titans', 'week': '17'},
    {'datetime': 'Sunday January 01 2017 13:00', 'home': 'Jacksonville Jaguars', 'away': 'Indianapolis Colts', 'week': '17'},
    {'datetime': 'Sunday January 01 2017 13:00', 'home': 'New England Patriots', 'away': 'Miami Dolphins', 'week': '17'},
    {'datetime': 'Sunday January 01 2017 13:00', 'home': 'New Orleans Saints', 'away': 'Atlanta Falcons', 'week': '17'},
    {'datetime': 'Sunday January 01 2017 13:00', 'home': 'New York Giants', 'away': 'Washington Redskins', 'week': '17'},
    {'datetime': 'Sunday January 01 2017 16:25', 'home': 'Arizona Cardinals', 'away': 'Los Angeles Rams', 'week': '17'},
    {'datetime': 'Sunday January 01 2017 16:25', 'home': 'Kansas City Chiefs', 'away': 'San Diego Chargers', 'week': '17'},
    {'datetime': 'Sunday January 01 2017 16:25', 'home': 'Oakland Raiders', 'away': 'Denver Broncos', 'week': '17'},
    {'datetime': 'Sunday January 01 2017 16:25', 'home': 'Seattle Seahawks', 'away': 'San Francisco 49ers', 'week': '17'}
]
