def includeme(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_route('about', '/about')
    config.add_route('admin', '/admin')
    config.add_route('home', '/')
    config.add_route('login', '/login')
    config.add_route('signup', '/signup')
    config.add_route('logout', '/logout')
    config.add_route('pool', '/pool')
    config.add_route('select', '/select')
    config.add_route('pick_test', '/pick_test')
